export const todoConstants = {
	FETCH_TODOS: 'FETCH_TODOS',
	TODOS_LOADING: 'TODOS_LOADING',
	ADD_TODO: 'ADD_TODO',
	DELETE_TODO: 'DELETE_TODO',
	SET_CURRENT_TODO: 'SET_CURRENT_TODO',
	SET_TODO_STATUS: 'SET_TODO_STATUS',
	CLEAR_CURRENT_TODO: 'CLEAR_CURRENT_TODO',
	EDIT_TODO: 'EDIT_TODO',
	TODO_ERROR: 'TODO_ERROR',
}
export const linkConstants = {
	FETCH_LINKS: 'FETCH_LINKS',
	LINKS_LOADING: 'LINKS_LOADING',
	ADD_LINK: 'ADD_LINK',
	DELETE_LINK: 'DELETE_LINK',
	SET_CURRENT_LINK: 'SET_CURRENT_LINK',
	SET_LINK_STATUS: 'SET_LINK_STATUS',
	CLEAR_CURRENT_LINK: 'CLEAR_CURRENT_LINK',
	EDIT_LINK: 'EDIT_LINK',
	LINK_ERROR: 'LINK_ERROR',
}

export const weatherConstants = {
	GET_GEOLOCATION: 'GET_GEOLOCATION',
	SET_COORDS: 'SET_COORDS',
	GEOLOCATION_DENIED: 'GEOLOCATION_DENIED',
	GET_CURRENT_WEATHER: 'GET_CURRENT_WEATHER',
	GET_WEATHER_FORECAST: 'GET_WEATHER_FORECAST',

	WEATHER_ERROR: 'WEATHER_ERROR'
}

export const quoteConstants = {
FETCH_QUOTES: 'FETCH_QUOTES',
FETCH_SINGLE_QUOTE: 'FETCH_SINGLE_QUOTE',
FAVORITE_QUOTE: 'FAVORITE_QUOTE',
ADD_QUOTE: 'ADD_QUOTE',
REMOVE_FAVORITED_QUOTE: 'REMOVE_FAVORITED_QUOTE',
QUOTE_ERROR: 'QUOTE_ERROR'
}

export const noteConstants = {
FETCH_NOTES: 'FETCH_NOTES',
ADD_NOTE: 'ADD_NOTE',
SET_CURRENT_NOTE: 'SET_CURRENT_NOTE',
UPDATE_NOTE: 'UPDATE_NOTE',
REMOVE_NOTE: 'REMOVE_NOTE',
NOTE_ERROR: 'NOTE_ERROR',
LOADING_NOTES: 'LOADING_NOTES'
}

export const focusConstants = {
	FETCH_FOCUS: 'FETCH_FOCUS',
	ADD_FOCUS: 'ADD_FOCUS',
	REMOVE_FOCUS: 'REMOVE_FOCUS',
	UPDATE_FOCUS: 'UPDATE_FOCUS',
	FOCUS_ERROR: 'FOCUS_ERROR'
}

export const themeConstants = {

UPDATE_THEME_COLOR: 'UPDATE_THEME_COLOR',
UPDATE_THEME_FONT: 'UPDATE_THEME_FONT'
}

export const backgroundConstants = {
	FETCH_ALL_BACKGROUNDS: 'FETCH_ALL_BACKGROUNDS',
	FETCH_BACKGROUND: 'FETCH_BACKGROUND',
	ADD_BACKGROUND: 'ADD_BACKGROUND',
	UPDATE_BACKGROUND: 'UPDATE_BACKGROUND',
	BACKGROUND_ERROR: 'BACKGROUND_ERROR',
	SET_BACKGROUND: 'SET_BACKGROUND',
}